getAuthorizationCode.js added to examples
green-api/whatsapp-api-client-js pull request #141
Opened 2024-05-17 10:56 UTC by tkulzhan

2024-05-19 12:52 UTC, Amele9 requested changes

2024-05-19 12:52 UTC, Amele9 commented on examples/getAuthorizationCode.js
> +})();s
Что за s?

2024-05-19 12:52 UTC, Amele9 commented on examples/getAuthorizationCode.js
> +        const response = await restAPI.instance.getAuthorizationCode(phoneNumber)
Необходимо скопировать пример из createGroupAndSendMessage.

2024-05-19 12:52 UTC, Amele9 commented on examples/getAuthorizationCode.js
> +const phoneNumber = 12345678910 // phone number to authorize
Не хватает `;`

2024-05-19 12:52 UTC, Amele9 commented on examples/getAuthorizationCode.js
> +})();s
И добавь перенос строки

2024-05-19 12:52 UTC, Amele9 commented on examples/getAuthorizationCode.js
> +        const response = await restAPI.instance.getAuthorizationCode(phoneNumber)
Старая версия библиотеки. Нет метода GetAuthorizationCode.

2024-05-20 08:46 UTC, tkulzhan commented on examples/getAuthorizationCode.js
> +        const response = await restAPI.instance.getAuthorizationCode(phoneNumber)
Нет есть

2024-06-03 05:18 UTC, Amele9 approved these changes

2024-06-03 05:18 UTC, merged